[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
stablecoin_factory = "8i6zoCxrUR8QgiRRHCkFXUJjgN3AAhJrTYXQFnueNGhq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
bind_address = "127.0.0.1"
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.program]]
name = "Token Metadata Program"
program_id = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program_path = "./metadata.so"